name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: "production"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Install Zola
        run: sudo snap install --edge zola

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >> ~/.ssh/config << EOF
          Host laniakeabooks-server
            HostName laniakeabooks.org
            User deploy
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          EOF
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build website
        run: zola build

      - name: Pull changes
        run: rsync -avz --progress --delete -e "ssh -i ~/.ssh/server.key" public/ deploy@laniakeabooks.org:/var/www/laniakea

      - name: Reload server
        run: ssh deploy@laniakeabooks.org 'sudo systemctl reload caddy'
